"""empty message

Revision ID: 0a1ebcbbe9ca
Revises: 
Create Date: 2021-04-26 04:12:12.259162

"""
from alembic import op
import noteit
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a1ebcbbe9ca'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('note',
    sa.Column('uid', noteit.extras.uuid.UUID(), nullable=False),
    sa.Column('secret', sa.String(length=64), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('post_date', sa.DateTime(), nullable=True),
    sa.Column('expiration_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('uid'),
    sa.UniqueConstraint('uid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('note')
    # ### end Alembic commands ###
